[build]
  command = "vite build"
  publish = "dist/client"
[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "https://www.guardemar.com/*"
  to = "https://guardemar.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/home-watch"
  to = "/home-watch-algarve/"
  status = 301

[[redirects]]
  from = "/home-watch/"
  to = "/home-watch-algarve/"
  status = 301

[[redirects]]
  from = "/property-handover"
  to = "/property-handover-algarve/"
  status = 301

[[redirects]]
  from = "/property-handover/"
  to = "/property-handover-algarve/"
  status = 301

[[redirects]]
  from = "/arrival-preparation"
  to = "/arrival-preparation-algarve/"
  status = 301

[[redirects]]
  from = "/arrival-preparation/"
  to = "/arrival-preparation-algarve/"
  status = 301

[[redirects]]
  from = "/property-care"
  to = "/property-management-algarve/"
  status = 301

[[redirects]]
  from = "/property-care/"
  to = "/property-management-algarve/"
  status = 301

[[redirects]]
  from = "/second-home-care-algarve"
  to = "/property-management-algarve/"
  status = 301

[[redirects]]
  from = "/second-home-care-algarve/"
  to = "/property-management-algarve/"
  status = 301

[[redirects]]
  from = "/holiday-home-care"
  to = "/property-management-algarve/"
  status = 301

[[redirects]]
  from = "/holiday-home-care/"
  to = "/property-management-algarve/"
  status = 301

[[redirects]]
  from = "/holiday-home-checks-algarve"
  to = "/home-watch-algarve/"
  status = 301

[[redirects]]
  from = "/holiday-home-checks-algarve/"
  to = "/home-watch-algarve/"
  status = 301

[[redirects]]
  from = "/vacant-property-inspections-algarve"
  to = "/home-watch-algarve/"
  status = 301

[[redirects]]
  from = "/vacant-property-inspections-algarve/"
  to = "/home-watch-algarve/"
  status = 301

[[redirects]]
  from = "/posts/:slug"
  to = "/blog/:slug"
  status = 301

[[redirects]]
  from = "/category/:category"
  to = "/blog/category/:category"
  status = 301
