import { createFileRoute, Link } from '@tanstack/react-router'
import { AssessmentCta, AuthorCard, Breadcrumbs, PageHero } from '@/components/site'
import { founder } from '@/config/site'

export const Route = createFileRoute('/about')({
  head: () => ({ meta: [{ title: 'About Guardemar and Hugo Gonçalves' }, { name: 'description', content: 'Why Hugo Gonçalves founded Guardemar to provide accountable property care for overseas owners in the Western Algarve.' }], links: [{ rel: 'canonical', href: 'https://guardemar.com/about/' }] }),
  component: AboutPage,
})

function AboutPage() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(founder.schema) }} /><Breadcrumbs items={[{ label: 'Home', to: '/' }, { label: 'About' }]} /><PageHero eyebrow="Why Guardemar exists" title="Someone local should know the property — and be accountable for checking it." text="Guardemar was founded to give overseas owners structured physical oversight of holiday homes and second homes across the Western Algarve." aside="Regular presence. Documented inspections. Clear communication. One accountable local point of contact." /><section className="section shell founder-story"><div><p className="eyebrow">Meet Hugo Gonçalves</p><h2>International experience, applied to a practical local problem.</h2></div><div><p>Guardemar was founded by Hugo Gonçalves, an entrepreneur with a background spanning international business, travel technology and risk management.</p><p>Hugo holds a degree in Business Management from the University of Hertfordshire and spent almost twenty years in global travel technology, including Hotelbeds / HBX Group. That work involved people, assets and businesses across multiple countries and markets.</p><p>He later founded <a href="https://adlerrochefort.com/en/" rel="external">Adler & Rochefort</a>, a specialist insurance and risk-management business serving private clients, professionals and businesses in Portugal.</p></div></section><section className="section warm-section"><div className="shell founder-story"><div><p className="eyebrow">From risk management to property care</p><h2>A recurring gap for owners living abroad.</h2></div><div><p>Working with international clients who own homes and assets in Portugal made one practical problem increasingly obvious: a property could be insured, maintained and secure, yet still have nobody providing structured physical oversight while the owner was away.</p><p>Guardemar grew from the same principle: an owner abroad should have one accountable local point of contact who understands the home, follows a consistent process and communicates clearly when something changes.</p><blockquote>Regular presence. Documented inspections. Clear accountability. Someone local who knows the property.</blockquote></div></div></section><section className="section shell"><AuthorCard /><div className="link-panel"><div><p className="eyebrow">How Guardemar works</p><p>Every relationship starts with the property: its access, systems, normal condition, existing contractors and the owner’s instructions.</p><Link to="/how-it-works/">Review the property-care process</Link></div><div><p className="eyebrow">Local presence</p><p>Guardemar serves the Western Algarve, from Carvoeiro to Sagres, with a deliberately focused service area.</p><Link to="/areas/">View local coverage</Link></div></div></section><AssessmentCta title="Talk to Hugo about your property in the Western Algarve." /></>
}
