import { createFileRoute, Link, notFound } from '@tanstack/react-router'
import { marked } from 'marked'
import { allPosts } from 'content-collections'
import BlogPosts from '@/components/blog-posts'
import { AssessmentCta, Breadcrumbs } from '@/components/site'
import { trackEvent } from '@/lib/analytics'

export const Route=createFileRoute('/blog/$slug')({loader:({params})=>{const post=allPosts.find(item=>item.slug===params.slug);if(!post)throw notFound();return post},head:({loaderData:post})=>({meta:[{title:`${post?.title} | Guardemar`},{name:'description',content:post?.summary},{property:'og:title',content:post?.title},{property:'og:description',content:post?.summary},{property:'og:type',content:'article'}],links:[{rel:'canonical',href:`https://guardemar.com/blog/${post?.slug}/`}]}),component:ArticlePage})
function ArticlePage(){const post=Route.useLoaderData();const related=allPosts.filter(item=>item.slug!==post.slug&&item.categories.some(category=>post.categories.includes(category))).slice(0,3);const schema={'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.summary,datePublished:post.date,author:{'@type':'Organization',name:'Guardemar'},publisher:{'@type':'Organization',name:'Guardemar'},mainEntityOfPage:`https://guardemar.com/blog/${post.slug}/`};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><Breadcrumbs items={[{label:'Home',to:'/'},{label:'Insights',to:'/blog/'},{label:post.title}]}/><article className="article"><header className="article-header shell"><p className="eyebrow">{post.categories.join(' · ')}</p><h1>{post.title}</h1><p>{post.summary}</p><div><span>By {post.author}</span><time dateTime={post.date}>{new Date(`${post.date}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</time><span>{post.readingTime} minute read</span></div></header><div className="article-hero-art shell"><span>GUARDEMAR / FIELD NOTES</span></div><div className="article-body" dangerouslySetInnerHTML={{__html:marked(post.content)}}/><div className="article-cta"><p>Need a reliable view of your own property?</p><Link to="/contact/" onClick={()=>trackEvent('blog_cta')}>Request a property assessment</Link></div></article>{related.length>0&&<section className="section shell"><p className="eyebrow">Related reading</p><BlogPosts posts={related}/></section>}<AssessmentCta/></>}
