export type ServicePage = {
  slug: string
  title: string
  seoTitle: string
  description: string
  eyebrow: string
  aside: string
  forWhom: string
  included: string[]
  excluded: string[]
  why: string
  scenario: string
}

export const servicePages = {
  'key-holding-algarve': {
    slug: 'key-holding-algarve', eyebrow: 'Key holding', title: 'Secure key holding for Algarve property owners.', seoTitle: 'Key Holding Algarve | Guardemar', description: 'Controlled key holding, authorised property access and visit records for second homes across the Western Algarve.', aside: 'Keys are coded and managed without attaching the complete property address.', forWhom: 'For overseas owners who need a dependable local keyholder for scheduled inspections, approved contractors, deliveries or urgent authorised access.', included: ['Coded key storage', 'Owner-approved access instructions', 'Access for Guardemar inspections', 'Contractor or delivery access by arrangement', 'A record of arranged attendance', 'A post-access visual check where agreed'], excluded: ['Unrestricted third-party access', '24-hour concierge cover', 'Responsibility for contractor workmanship', 'Keys labelled with a complete property address'], why: 'Informal key circulation can make it difficult to know who entered a property and when. A controlled process creates accountability and makes practical local action possible when the owner is abroad.', scenario: 'A plumber needs access after moisture is found below a sink. Guardemar confirms the owner’s instruction, meets the contractor, records attendance and reports the visible condition afterwards.',
  },
  'vacant-property-inspections-algarve': {
    slug: 'vacant-property-inspections-algarve', eyebrow: 'Vacant property inspections', title: 'Structured inspections for vacant Algarve homes.', seoTitle: 'Vacant Property Inspections Algarve | Guardemar', description: 'Scheduled visual inspections and photo reports for vacant villas, apartments and second homes in the Western Algarve.', aside: 'A repeatable, non-invasive condition check while nobody is living in the property.', forWhom: 'For owners leaving a home empty for several weeks or months, including between seasonal visits, during a sale, after completion or whilst maintenance is being organised.', included: ['Security and access checks', 'Visible water and moisture checks', 'Humidity and mould indicators', 'Electrical status where agreed', 'Windows, shutters and doors', 'Exterior, pool and garden visual condition', 'Photographs and issue priority'], excluded: ['Structural surveys', 'Invasive defect investigation', 'Electrical, plumbing or pool certification', 'A guarantee that concealed defects will be detected'], why: 'An occupied home produces everyday warning signs. In a vacant property, a slow leak, failed irrigation zone, damp patch or damaged shutter may remain unnoticed until the next trip.', scenario: 'An owner leaves Portugal for four months. Guardemar follows the same property-specific checklist on each visit, records changes and escalates anything marked ATTENTION or URGENT.',
  },
  'holiday-home-checks-algarve': {
    slug: 'holiday-home-checks-algarve', eyebrow: 'Holiday home checks', title: 'Practical checks between visits to your Algarve home.', seoTitle: 'Holiday Home Checks Algarve | Guardemar', description: 'Documented holiday-home checks covering access, leaks, humidity, electrics, pool, garden and visible property condition.', aside: 'Built for intermittently occupied homes, not guest bookings or rental calendars.', forWhom: 'For owners who use their Algarve property themselves, lend it to family or occupy it intermittently without needing a rental-management company.', included: ['Agreed interior and exterior checks', 'Visible leak and damp indicators', 'Doors, windows and shutters', 'Mail and obvious access concerns', 'Pool and irrigation visual condition', 'Digital report with photographs', 'Recommended next action'], excluded: ['Guest management', 'Cleaning turnovers', 'Booking administration', 'Technical diagnosis or repair'], why: 'A second home still needs observation between stays. Regular checks create continuity and help the owner return with fewer unknowns.', scenario: 'A villa is used during school holidays but remains closed between visits. Scheduled checks record humidity, plumbing, security, pool and garden condition without turning the home into a rental operation.',
  },
  'property-handover-algarve': {
    slug: 'property-handover-algarve', eyebrow: 'Property handover', title: 'Create a clear baseline for a newly acquired Algarve home.', seoTitle: 'Property Handover Algarve | Guardemar', description: 'Property handover support, access records, inventory photography and a practical care baseline for overseas owners.', aside: 'A documented starting point after completion, refurbishment or a change of local arrangements.', forWhom: 'For owners completing a purchase, taking back a property from another manager, finishing building work or establishing a new local care routine.', included: ['Key and access review', 'Property profile and owner instructions', 'Baseline condition photographs', 'Visible utilities and system status', 'Contractor and condominium contacts', 'Immediate care priorities', 'Recommended inspection scope'], excluded: ['Snagging surveys', 'Legal completion services', 'Building certification', 'Valuation or technical due diligence'], why: 'A useful property-care relationship starts with accurate information. A handover records what is present, who has access and which systems or issues require follow-up.', scenario: 'After purchasing a villa, an overseas owner needs keys collected, existing providers documented and the visible property condition recorded before leaving Portugal.',
  },
  'arrival-preparation-algarve': {
    slug: 'arrival-preparation-algarve', eyebrow: 'Arrival preparation', title: 'Arrive at your Algarve home informed and prepared.', seoTitle: 'Arrival Preparation Algarve | Guardemar', description: 'Pre-arrival property checks and practical coordination for owners returning to a second home in the Western Algarve.', aside: 'A final documented check before travel, with issues raised while there is still time to act.', forWhom: 'For owners returning after a longer absence, travelling with family or guests, or arriving after maintenance work has taken place.', included: ['Pre-arrival visual inspection', 'Water and power status where agreed', 'Hot water and air-conditioning checks where agreed', 'Pool and garden visual condition', 'Ventilation and basic property readiness', 'Coordination with cleaners or contractors', 'Arrival report and photographs'], excluded: ['Hotel-style concierge services', 'Guaranteed repair completion', 'Specialist appliance certification', 'Cleaning or technical work unless separately arranged'], why: 'Travel is easier when the owner knows the current condition before boarding a flight. A pre-arrival check creates time to address visible problems rather than discovering them at the door.', scenario: 'Two days before arrival, Guardemar checks the home, confirms agreed systems, photographs the pool and garden and flags an air-conditioning concern for specialist follow-up.',
  },
  'storm-property-checks-algarve': {
    slug: 'storm-property-checks-algarve', eyebrow: 'Post-weather checks', title: 'Visual property checks after significant Algarve weather.', seoTitle: 'Storm Property Checks Algarve | Guardemar', description: 'Post-weather visual checks for shutters, exterior areas, drainage, pools and gardens, subject to safe access and availability.', aside: 'Photographic confirmation after significant local weather — without unrealistic monitoring promises.', forWhom: 'For owners concerned about a specific period of strong wind or rain affecting an unoccupied home, particularly in exposed coastal locations.', included: ['External access and visible security', 'Shutters, windows and doors', 'Terraces and visible drainage', 'Fallen branches or displaced items', 'Pool and garden condition', 'Interior signs of water entry where accessible', 'Photographs and issue escalation'], excluded: ['Emergency-services response', 'Roof access or work at height', 'Structural assessment', 'Guaranteed inspection after every weather event'], why: 'Atlantic weather affects Western Algarve locations differently. A timely visual record can confirm that the home appears unchanged or identify a concern requiring a qualified contractor.', scenario: 'After a period of strong wind in Sagres, Guardemar attends when conditions and access are safe, checks agreed areas and sends dated photographs to the owner.',
  },
  'contractor-access-algarve': {
    slug: 'contractor-access-algarve', eyebrow: 'Contractor access', title: 'Accountable local access for Algarve property works.', seoTitle: 'Contractor Access Algarve | Guardemar', description: 'Authorised contractor access, attendance records and visible follow-up for overseas property owners in the Western Algarve.', aside: 'One local point of contact for access and communication; qualified trades remain responsible for their work.', forWhom: 'For owners who already have a plumber, electrician, pool company, gardener or other provider but cannot attend the appointment in person.', included: ['Confirming owner instructions', 'Opening and securing the property', 'Recording contractor attendance', 'Sharing relevant access information', 'Visible post-visit photographs where agreed', 'Relaying practical updates', 'Coordinating follow-up appointments'], excluded: ['Technical supervision', 'Certification of completed work', 'Acceptance of quotations without authority', 'Responsibility for quality, safety or workmanship'], why: 'Contractor visits can otherwise depend on neighbours, loose keys or incomplete information. Managed access gives the owner a clear record and reduces uncertainty.', scenario: 'An electrician needs to investigate a reported fault. Guardemar provides authorised access, remains the practical contact and reports the visible state after the appointment.',
  },
} satisfies Record<string, ServicePage>
