import { Link } from '@tanstack/react-router'
import { Check, Minus } from 'lucide-react'
import { AssessmentCta, Breadcrumbs, ButtonLink, PageHero } from '@/components/site'
import { areas, plans } from '@/config/site'
import type { ServicePage } from '@/config/services'

export function DeepServicePage({ service }: { service: ServicePage }) {
  const schema = { '@context': 'https://schema.org', '@type': 'Service', name: service.eyebrow, description: service.description, url: `https://guardemar.com/${service.slug}/`, provider: { '@id': 'https://guardemar.com/#business' }, areaServed: { '@type': 'Place', name: 'Western Algarve, Portugal' } }
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><Breadcrumbs items={[{ label: 'Home', to: '/' }, { label: 'Services', to: '/services/' }, { label: service.eyebrow }]} /><PageHero eyebrow={service.eyebrow} title={service.title} text={service.description} aside={service.aside} /><section className="section shell service-depth"><div className="content-block"><p className="eyebrow">Who it is for</p><h2>A practical service for owners who are away.</h2><p>{service.forWhom}</p><p>{service.why}</p><ButtonLink to="/contact/" event="service_cta_click">Request a Property Assessment</ButtonLink></div><div className="scope-card"><div><p className="eyebrow">Included</p><ul>{service.included.map(item => <li key={item}><Check size={16} />{item}</li>)}</ul></div><div><p className="eyebrow">Not included</p><ul>{service.excluded.map(item => <li key={item}><Minus size={16} />{item}</li>)}</ul></div></div></section><section className="section warm-section"><div className="shell scenario-grid"><div><p className="eyebrow">Typical scenario</p><h2>What this looks like in practice.</h2></div><p className="large-copy">{service.scenario}</p></div></section><section className="section shell link-panel"><div><p className="eyebrow">Plan the right level of care</p><h2>Use this service within a clear property routine.</h2><p>Guardemar plans start from €{plans[0].price} per month, with the final scope confirmed after assessing the property.</p><Link to="/plans">Compare care plans</Link> · <Link to="/inspection-checklist">Review the inspection checklist</Link></div><div><p className="eyebrow">Western Algarve coverage</p><p>{Object.values(areas).slice(0, 5).map(area => area.name).join(' · ')} and west to Sagres.</p><Link to="/areas">View all service areas</Link></div></section><AssessmentCta title="Put a clear local process around your property." /></>
}
